apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-crux-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  tm.pub: |-
  tm.key: |-
