apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-quorum-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  password.txt: |-
  nodekey1: |-
  nodekey2: |-
