apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-crux
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - name: constellation
    port: 9000
    targetPort: 9000
  selector:
    app: {{ .Release.Name }}-quorum-crux
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-quorumtx
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - name: tx
    port: 30303
    targetPort: 30303
  selector:
    {{- include "node.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-quorumtx-replica1
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - name: tx
    port: 30303
    targetPort: 30303
  selector:
    {{- include "node.replica1.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-quorumtx-replica2
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - name: tx
    port: 30303
    targetPort: 30303
  selector:
    {{- include "node.replica2.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rpc
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - name: rpc
    port: 8545
    targetPort: 8545
  - name: ws
    port: 8546
    targetPort: 8546
  selector:
    app: {{ .Release.Name }}-quorum-crux
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-explorer
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  ports:
  - name: backend
    port: 80
    targetPort: 22004
  selector:
    {{- include "nodemanager.selectorLabels" . | nindent 4 }}
